name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup GitHub Actions
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build the Solution
      run: dotnet build ANXY.sln
      
    - name: DotNet Test
      run: dotnet test ANXY.sln
