name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup GitHub Actions
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore NuGet packages
      run: nuget restore ANXY.sln
      
    - name: Build the Solution
      run: msbuild ANXY.sln
