name: Main Branch PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version:
          6.0.x
          
    - name: Install .NET dependencies
      run: dotnet restore
      
    - name: Build the Solution
      run: dotnet build ANXY.sln
      
    - name: .NET Test
      run: dotnet test ANXY.sln
